# Generated by Django 5.2.3 on 2025-07-03 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='color',
            field=models.CharField(default='#808080', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX, например "#FFAA00".', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет (HEX)'),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='color',
            field=models.CharField(default='#808080', max_length=7, validators=[django.core.validators.RegexValidator(message='Введите цвет в формате HEX, например "#FFAA00".', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Цвет (HEX)'),
        ),
    ]
